# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer1', models.CharField(blank=True, max_length=254)),
                ('answer2', models.CharField(blank=True, max_length=254)),
                ('answer3', models.CharField(blank=True, max_length=254)),
                ('answer4', models.CharField(blank=True, max_length=254)),
                ('answer5', models.CharField(blank=True, max_length=254)),
                ('answer6', models.CharField(blank=True, max_length=254)),
                ('answer7', models.CharField(blank=True, max_length=254)),
                ('answer8', models.CharField(blank=True, max_length=254)),
                ('answer9', models.CharField(blank=True, max_length=254)),
                ('answer10', models.CharField(blank=True, max_length=254)),
                ('answer11', models.CharField(blank=True, max_length=254)),
                ('answer12', models.CharField(blank=True, max_length=254)),
                ('answer13', models.CharField(blank=True, max_length=254)),
                ('answer14', models.CharField(blank=True, max_length=254)),
                ('answer15', models.CharField(blank=True, max_length=254)),
                ('answer16', models.CharField(blank=True, max_length=254)),
                ('answer17', models.CharField(blank=True, max_length=254)),
                ('answer18', models.CharField(blank=True, max_length=254)),
                ('answer19', models.CharField(blank=True, max_length=254)),
                ('answer20', models.CharField(blank=True, max_length=254)),
                ('answer21', models.TextField(default='')),
                ('answer22', models.TextField(default='')),
                ('answer23', models.TextField(default='')),
                ('answer24', models.TextField(default='')),
                ('answer25', models.TextField(default='')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('medical_history', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chambermaid.Case')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=254)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('mobile_number', models.CharField(max_length=11)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=254)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRatingScale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chambermaid.Project')),
            ],
        ),
        migrations.CreateModel(
            name='RatingScale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sort_index', models.IntegerField(db_index=True)),
                ('statement', models.TextField()),
                ('description', models.TextField()),
                ('question_type', models.CharField(choices=[('1', 'Numeric Selection'), ('2', 'Character Selection'), ('3', 'True or False'), ('4', 'Text')], max_length=2)),
                ('options', models.TextField()),
                ('rating_scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chambermaid.RatingScale')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_index', models.IntegerField(blank=True)),
                ('label', models.CharField(db_index=True, max_length=254, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_code', models.CharField(blank=True, max_length=254)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='type',
            name='type_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chambermaid.TypeGroup'),
        ),
        migrations.AddField(
            model_name='projectratingscale',
            name='rating_scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chambermaid.RatingScale'),
        ),
        migrations.AddField(
            model_name='project',
            name='rating_scales',
            field=models.ManyToManyField(through='chambermaid.ProjectRatingScale', to='chambermaid.RatingScale'),
        ),
        migrations.AddField(
            model_name='casetype',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chambermaid.Type'),
        ),
        migrations.AddField(
            model_name='case',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chambermaid.Patient'),
        ),
        migrations.AddField(
            model_name='case',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chambermaid.Project'),
        ),
        migrations.AddField(
            model_name='case',
            name='types',
            field=models.ManyToManyField(through='chambermaid.CaseType', to='chambermaid.Type'),
        ),
        migrations.AddField(
            model_name='answersheet',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chambermaid.Case'),
        ),
        migrations.AddField(
            model_name='answersheet',
            name='rating_scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chambermaid.RatingScale'),
        ),
    ]
