# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 15:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chambermaid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 29, 15, 31, 19, 354445, tzinfo=utc)),
        ),
    ]
