# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 16:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chambermaid', '0002_patient_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer1', models.CharField(max_length=254)),
                ('answer2', models.CharField(max_length=254)),
                ('answer3', models.CharField(max_length=254)),
                ('answer4', models.CharField(max_length=254)),
                ('answer5', models.CharField(max_length=254)),
                ('answer6', models.CharField(max_length=254)),
                ('answer7', models.CharField(max_length=254)),
                ('answer8', models.CharField(max_length=254)),
                ('answer9', models.CharField(max_length=254)),
                ('answer10', models.CharField(max_length=254)),
                ('answer11', models.CharField(max_length=254)),
                ('answer12', models.CharField(max_length=254)),
                ('answer13', models.CharField(max_length=254)),
                ('answer14', models.CharField(max_length=254)),
                ('answer15', models.CharField(max_length=254)),
                ('answer16', models.CharField(max_length=254)),
                ('answer17', models.CharField(max_length=254)),
                ('answer18', models.CharField(max_length=254)),
                ('answer19', models.CharField(max_length=254)),
                ('answer20', models.CharField(max_length=254)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2017, 8, 31, 16, 38, 2, 623278, tzinfo=utc), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2017, 8, 31, 16, 38, 2, 622302, tzinfo=utc), editable=False)),
                ('medical_history', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('index', models.IntegerField()),
                ('statement', models.TextField()),
                ('options', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RatingScale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=254, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 31, 16, 38, 2, 620296, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='project',
            name='rating_scales',
            field=models.ManyToManyField(to='chambermaid.RatingScale'),
        ),
        migrations.AddField(
            model_name='item',
            name='rating_scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chambermaid.RatingScale'),
        ),
        migrations.AddField(
            model_name='case',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chambermaid.Patient'),
        ),
        migrations.AddField(
            model_name='case',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chambermaid.Project'),
        ),
        migrations.AddField(
            model_name='case',
            name='types',
            field=models.ManyToManyField(to='chambermaid.Type'),
        ),
        migrations.AddField(
            model_name='answersheet',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chambermaid.Case'),
        ),
        migrations.AddField(
            model_name='answersheet',
            name='rating_scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chambermaid.RatingScale'),
        ),
    ]
