# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chambermaid', '0003_auto_20170901_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sort_index', models.IntegerField(db_index=True)),
                ('statement', models.TextField()),
                ('description', models.TextField()),
                ('question_type', models.CharField(choices=[('1', 'Numeric Selection'), ('2', 'Character Selection'), ('3', 'True or False'), ('4', 'Text')], max_length=2)),
                ('options', models.TextField()),
                ('rating_scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chambermaid.RatingScale')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='rating_scale',
        ),
        migrations.AddField(
            model_name='answersheet',
            name='answer21',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='answersheet',
            name='answer22',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='answersheet',
            name='answer23',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='answersheet',
            name='answer24',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='answersheet',
            name='answer25',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='case',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='type',
            name='label',
            field=models.CharField(db_index=True, max_length=254, unique=True),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
