# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chambermaid', '0004_auto_20170904_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheet',
            name='answer1',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='answer10',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='answer11',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='answer12',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='answer13',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='answer14',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='answer15',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='answer16',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='answer17',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='answer18',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='answer19',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='answer2',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='answer20',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='answer3',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='answer4',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='answer5',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='answer6',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='answer7',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='answer8',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='answer9',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
