# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chambermaid', '0005_auto_20170904_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='type',
            name='model_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chambermaid.TypeGroup'),
            preserve_default=False,
        ),
    ]
